apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resources-api-fusion-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: ingress-nginx-fusiondev
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: ingress-nginx-fusiondev
  tls:
    - hosts:
        - fra-resources.{{ENVNAME}}.api.fusion-dev.net
      secretName: wildcard-fusiondev-tls-cert
  rules:
    - host: fra-resources.{{ENVNAME}}.api.fusion-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resources-api
                port:
                  number: 80
