parameters:
  environment: ''
  clientId: ''
  sqlServer: ''
  clientSecretName: 'ClientSecret-Resources-Test'
  azureSubscription: 'FRA Automation Non-Prod'
  coreAzureSubscription: ''
  
steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: 'Ensure environment resource group'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      ScriptType: FilePath
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptPath: infrastructure/scripts/ensure-resourcegroup.ps1
      ScriptArguments: -environment ${{ parameters.environment }}

 ## DATABASE SHOULD BE DEPLOYED BY API PIPELINE, NOT INFRA
 ## TODO - Move provisioning of db to api pipeline

  - task: AzurePowerShell@5
    displayName: 'Deploy sql database'
    inputs:
      azureSubscription: ${{ parameters.coreAzureSubscription }}
      ScriptType: FilePath
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptPath: infrastructure/scripts/deploy-database.ps1
      ScriptArguments: -environment ${{ parameters.environment }} -sqlServerName ${{ parameters.sqlServer }}

  - task: AzurePowerShell@5
    displayName: 'Grant azure ad app sql database access'
    inputs:
      azureSubscription: ${{ parameters.coreAzureSubscription }}
      ScriptType: FilePath
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptPath: infrastructure/scripts/grant-adapp-sql-access.ps1
      ScriptArguments: -clientId ${{ parameters.clientId }} -sqlServerName ${{ parameters.sqlServer }} -sqlDatabaseName $(SqlDatabaseName)

  - script: |
      dotnet restore infrastructure/tooling/fusion-infra-cli/Fusion.Infra.Cli/Fusion.Infra.Cli.csproj
      dotnet pack infrastructure/tooling/fusion-infra-cli/Fusion.Infra.Cli/Fusion.Infra.Cli.csproj
      dotnet tool install -g --add-source infrastructure/tooling/fusion-infra-cli/Fusion.Infra.Cli/nupkg fusion.infra.cli
    displayName: "Install fusion infra cli tool"

  - task: AzureCLI@2
    displayName: Create database
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: pscore
      scriptLocation: inlineScript        
      inlineScript: |
        finf database provision `
          --url https://ci.infrasupport.api.fusion-dev.net/ `
          -f ./src/backend/infrastructure/fusion-db-config.json `
          -e "${{ parameters.environment }}" `
          --sql-contributor-client-id ${{ parameters.clientId }}


  - task: AzurePowerShell@5
    displayName: 'Deploy ARM template'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      ScriptType: FilePath
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptPath: infrastructure/scripts/deploy-resources.ps1
      ScriptArguments: -environment ${{ parameters.environment }} -clientId ${{ parameters.clientId }}
      
  