
parameters:
    project: ''
  
stages:
  - stage: BuildFunction
    displayName: Build Function Project
    jobs:
    - job: Build
      pool: 
        vmImage: 'windows-latest'
      variables:
        projectPath: src/backend/functions/${{ parameters.project }}
        projectName: ${{ parameters.project }}
  
      steps:
      - script: |
          dotnet restore $(projectPath)/Fusion.Resources.Functions.csproj
          dotnet build $(projectPath)/Fusion.Resources.Functions.csproj --configuration Release

      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          arguments: '--configuration Release --output $(Build.BinariesDirectory)'
          projects: '$(projectPath)/*.csproj'
          publishWebProjects: false
          modifyOutputPath: true
          zipAfterPublish: false

      - task: ArchiveFiles@2
        displayName: 'Compress published function to zip'
        inputs:
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).zip'
  
      - task: DeleteFiles@1
        displayName: 'Delete files from $(Build.BinariesDirectory)'
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)'
          Contents: '*'
  
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'