apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  labels: 
    environment: {{ENVNAME}}
type: Opaque
stringData:
  appsettings.secrets.yaml: |
    {
      "AzureAd": {
        "ClientSecret": "{{clientSecret}}"
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: summary-api
  template:
    metadata:
      labels:
        app: summary-api
    spec:
      volumes:
      - name: env-secrets-volumes
        secret: 
          secretName: env-secrets

      containers:
      - name: summary-api
        image: {{fusionAcr}}/{{imageName}}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: env-secrets-volumes
          mountPath: "/app/secrets" 
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "{{instrumentationKey}}"
        - name: KEYVAULT_URL
          value: "{{envKeyVaultUrl}}"
        - name: ENVNAME
          value: "{{ENVNAME}}"
        - name: FUSION_ENVIRONMENT
          value: "{{fusionEnvironment}}"
        - name: AzureAd__ClientId
          value: "{{clientId}}"
        resources:
          requests:
            memory: "250Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        args:
        - /server

        livenessProbe:
          httpGet:
            path: /_health/liveness
            port: 8080
          failureThreshold: 10
          timeoutSeconds: 30
          initialDelaySeconds: 60
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /_health/readiness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: summary-api
spec:
  selector:
    app: summary-api
  ports:
  - port: 80
    targetPort: 8080
