apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: summary-api-fusiondev-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fra-summary.{{ENVNAME}}.api.fusion-dev.net
      secretName: wildcard-tls-cert
  rules:
    - host: fra-summary.{{ENVNAME}}.api.fusion-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: summary-api
                port:
                  number: 80
