#PS! 
#secret pr.fusion-dev.net-tls must exist for this deployment to work. Since it contains secret information, it cannot be added to source control.

apiVersion: v1
kind: Secret
metadata:
  name: summary-api-env-secrets
  labels: 
    environment: pr
type: Opaque
stringData:
  appsettings.secrets.yaml: |
    {
      "AzureAd": {
        "ClientSecret": "{{clientSecret}}"
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'summary-api-pr-{{prNumber}}'
  labels: 
    environment: pr
    prNumber: '{{prNumber}}'
  annotations:
    k8s-ttl-controller.twin.sh/ttl: '3d'    
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: 'summary-api-pr-{{prNumber}}'
  template:
    metadata:
      labels:
        app: 'summary-api-pr-{{prNumber}}'
    spec:
      volumes:
      - name: env-secrets-volumes
        secret: 
          secretName: summary-api-env-secrets

      containers:
      - name: summary-api-pr-{{prNumber}}
        image: {{fusionAcr}}/{{imageName}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: env-secrets-volumes
          mountPath: "/app/secrets" 
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "{{instrumentationKey}}"
        - name: KEYVAULT_URL
          value: "{{envKeyVaultUrl}}"
        - name: ENVNAME
          value: "{{ENVNAME}}"
        - name: FUSION_ENVIRONMENT
          value: "{{fusionEnvironment}}"
        - name: AzureAd__ClientId
          value: "{{clientId}}"
        - name: BuildNr
          value: "{{buildNr}}"
        - name: PULL_REQUEST_ID
          value: "{{prNumber}}"
        args:
        - /server

        livenessProbe:
          httpGet:
            path: /_health/liveness
            port: 8080
          failureThreshold: 10
          timeoutSeconds: 30
          initialDelaySeconds: 60
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /_health/readiness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: summary-api-pr-{{prNumber}}
  labels: 
    environment: pr
    prNumber: '{{prNumber}}'
  annotations:
    k8s-ttl-controller.twin.sh/ttl: '3d'    

spec:
  selector:
    app: summary-api-pr-{{prNumber}}
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: summary-api-fusion-ingress-{{prNumber}}
  labels: 
    environment: pr
    prNumber: '{{prNumber}}'
  annotations:
    k8s-ttl-controller.twin.sh/ttl: '3d'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    fusion-health/environment: 'pr'
    fusion-health/application: 'Fusion Summary'
    fusion-health/url: /_health/ready
spec:
  ingressClassName: ingress-nginx-fusiondev
  tls:
  - hosts:
    - fra-summary-{{prNumber}}.pr.api.fusion-dev.net
    secretName: wildcard-fusiondev-tls-cert

  rules:
    - host: fra-summary-{{prNumber}}.pr.api.fusion-dev.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: summary-api-pr-{{prNumber}}
              port:
                number: 80
