trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - src/backend/infrastructure/*
  
pr: none
  
stages:
- stage: DeployCI
  displayName: CI Azure Infra
  jobs:
  - deployment: DeployInfra
    environment: fusion-ci
    variables:
      environmentName: ci
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/arm-environments.yml
            parameters:
              environment: $(environmentName)
              clientId: 5a842df8-3238-415d-b168-9f16a6a6031b
              sqlServer: fusion-test-sqlserver
              azureSubscription: FRA Automation Non-Prod

- stage: DeployPR
  displayName: PR Azure Infra
  dependsOn: DeployCI
  condition: succeeded()
  jobs:
  - deployment: DeployInfra
    environment: fusion-pullrequests
    variables:
      environmentName: pr
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/arm-environments.yml
            parameters:
              environment: $(environmentName)
              clientId: 5a842df8-3238-415d-b168-9f16a6a6031b
              sqlServer: fusion-test-sqlserver
              azureSubscription: FRA Automation Non-Prod

          ## To get the pr slots to talk to the correct databases, we need to kill the key vault secret for connection string.
          ## The secret would override the direct env property used to target the correct db.
          - task: AzurePowerShell@5
            displayName: 'Remove db connection string secret'
            inputs:
              azureSubscription: 'PROJECT_PORTAL (63b791ae-b2bc-41a1-ac66-806c4e69bffe)'
              ScriptType: InlineScript
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
              Inline: |
                Write-Host "Deleting secret @ kv-fap-resources-pr/ConnectionStrings--ResourcesDbContext"
                Remove-AzKeyVaultSecret -VaultName kv-fap-resources-pr -Name ConnectionStrings--ResourcesDbContext -Force


- stage: DeployQA
  displayName: QA Azure Infra
  dependsOn: DeployCI
  condition: succeeded()
  jobs:
  - deployment: DeployInfra
    environment: fusion-fqa
    variables:
      environmentName: fqa
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/arm-environments.yml
            parameters:
              environment: $(environmentName)
              clientId: 5a842df8-3238-415d-b168-9f16a6a6031b
              sqlServer: fusion-test-sqlserver
              azureSubscription: FRA Automation Non-Prod

- stage: DeployTR
  displayName: TR Azure Infra
  dependsOn: DeployCI
  condition: succeeded()
  jobs:
  - deployment: DeployInfra
    environment: fusion-tr
    variables:
      environmentName: tr
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/arm-environments.yml
            parameters:
              environment: $(environmentName)
              clientId: 5a842df8-3238-415d-b168-9f16a6a6031b
              sqlServer: fusion-test-sqlserver
              azureSubscription: FRA Automation Non-Prod

- stage: DeployPROD
  displayName: PROD Azure Infra
  dependsOn: DeployQA
  condition: succeeded()
  jobs:
  - deployment: DeployInfra
    environment: fusion-prod
    variables:
      environmentName: fprd
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/arm-environments.yml
            parameters:
              environment: $(environmentName)
              clientId: 97978493-9777-4d48-b38a-67b0b9cd88d2
              sqlServer: fusion-prod-sqlserver
              clientSecretName: ClientSecret-Resources-Prod
              azureSubscription: FRA Automation Prod
                    