name: $(date:yyyyMMdd)$(rev:.r)

trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - src/backend/function/*
    - src/backend/integration/*

pr: none
  
variables:
    subscriptionService: 'PROJECT_PORTAL (63b791ae-b2bc-41a1-ac66-806c4e69bffe)'
    webPackage: '$(Pipeline.Workspace)/drop/Fusion.Resources.Functions.zip'
  
stages:
    - template: templates/build-function.yml
      parameters:
        project: 'Fusion.Resources.Functions'


    - stage: DeployCI
      displayName: CI
      dependsOn: BuildFunction
      condition: succeeded()
      
      variables:
        environment: 'ci'
        functionServiceName: func-fap-resources-$(environment)
    
      jobs:
      - deployment: Deploy
        pool: Private Docker
    
        displayName: 'Deploy function app'
        environment: fusion-ci
    
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-function-template.yml
                  parameters:
                    envName: $(environment)
                    clientId: '5a842df8-3238-415d-b168-9f16a6a6031b'

                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(subscriptionService)
                    appType: 'functionApp'
                    appName: $(functionServiceName)
                    package: $(webPackage)
                    deploymentMethod: 'runFromPackage'

    - stage: DeployFQA
      displayName: FQA
      dependsOn: DeployCI
      condition: succeeded()
      
      variables:
        environment: 'fqa'
        functionServiceName: func-fap-resources-$(environment)
    
      jobs:
      - deployment: Deploy
        pool: Private Docker
    
        displayName: 'Deploy function app'
        environment: fusion-resources-fqa
    
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-function-template.yml
                  parameters:
                    envName: $(environment)
                    clientId: '5a842df8-3238-415d-b168-9f16a6a6031b'
                    fusionEnvironment: fqa
                    
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(subscriptionService)
                    appType: 'functionApp'
                    appName: $(functionServiceName)
                    package: $(webPackage)
                    deploymentMethod: 'runFromPackage'

    - stage: DeployFPRD
      displayName: FPRD
      dependsOn: DeployFQA
      condition: succeeded()
      
      variables:
        environment: 'fprd'
        functionServiceName: func-fap-resources-$(environment)
    
      jobs:
      - deployment: Deploy
        pool: Private Docker
    
        displayName: 'Deploy function app'
        environment: fusion-prod
    
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-function-template.yml
                  parameters:
                    envName: $(environment)
                    clientId: '97978493-9777-4d48-b38a-67b0b9cd88d2'
                    fusionResource: '97978493-9777-4d48-b38a-67b0b9cd88d2'
                    fusionEnvironment: fprd
                    
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(subscriptionService)
                    appType: 'functionApp'
                    appName: $(functionServiceName)
                    package: $(webPackage)
                    deploymentMethod: 'runFromPackage'