name: $(date:yyyyMMdd)$(rev:.r)
trigger: none
pr: none

resources:
    repositories:
      - repository: commonTemplates
        type: git
        name: 'ProView Portal/fusion-pipeline-templates'
  
variables:
    subscriptionService: 'PROJECT_PORTAL (63b791ae-b2bc-41a1-ac66-806c4e69bffe)'
    webPackage: '$(Pipeline.Workspace)/drop/Fusion.Resources.Functions.zip'
  
stages:
    - template: templates/build-function.yml
      parameters:
        project: 'Fusion.Resources.Functions'


    - stage: DeployCI
      displayName: CI
      dependsOn: BuildFunction
      condition: succeeded()
      
      variables:
        environment: 'ci'
        functionServiceName: func-fap-resources-$(environment)
    
      jobs:
      - deployment: Deploy
        pool: Private Docker
    
        displayName: 'Deploy api'
        environment: fusion-ci
    
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-function-template.yml
                  parameters:
                    envName: $(environment)
                    clientId: '5a842df8-3238-415d-b168-9f16a6a6031b'

                - task: AzureRmWebAppDeployment@3
                  displayName: 'Deploy service bin files'
                  inputs:
                    azureSubscription: $(subscriptionService)
                    WebAppName: $(functionServiceName)
                    Package: $(webPackage)
                    useCustomDeployment: true
                    deploymentMethod: 'webDeploy'
                    appOffline: true
                    removeAdditionalFilesFlag: true
                    renameFilesFlag: true
                
                - task: AzureAppServiceManage@0
                  displayName: 'Restart function app'
                  inputs:
                    azureSubscription: $(subscriptionService)
                    WebAppName: $(functionServiceName)
                    Action: 'Restart Azure App Service'
                    
                    
  