name: $(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'ubuntu-latest'

trigger: none

pr: 
  branches:
    include:
    - master
  paths:
    include:
    - src/backend/function/*
    - src/backend/integration/*
  
variables:
    subscriptionService: 'FRA Automation Non-Prod'
    webPackage: '$(Pipeline.Workspace)/drop/Fusion.Resources.Functions.zip'
    prNumber: $(System.PullRequest.PullRequestNumber)
  
stages:
    - template: templates/build-function.yml
      parameters:
        project: 'Fusion.Resources.Functions'


    - stage: DeployPR
      displayName: PR
      dependsOn: BuildFunction
      condition: succeeded()
      
      variables:
        environment: 'pr'
        functionServiceName: func-fap-resources-$(environment)
    
      jobs:
      - deployment: Deploy
    
        displayName: 'Deploy function app'
        environment: fra-pr
    
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-function-pr-template.yml
                  parameters:
                    envName: $(environment)
                    clientId: '5a842df8-3238-415d-b168-9f16a6a6031b'
                    pullRequestNumber: $(prNumber)

                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(subscriptionService)
                    appType: 'functionApp'
                    appName: $(functionServiceName)
                    package: $(webPackage)
                    deploymentMethod: 'runFromPackage'