pr: none

stages:
  # BUILD
  ###################################################################################################################
  - stage: Build
    displayName: Build Resources
  
    jobs:
    - job: Build
      pool: Private Docker
      displayName: 'Build resources bundle'
      
      variables:
        image: fusion-app-resources:$(Build.BuildNumber)
        container: app-resources-$(Build.BuildNumber)
    
      steps:
      - script: |
          docker build -f src/frontend/build.Dockerfile src/frontend/ -t $(image)
        displayName: 'Build dockerfile src/frontend/build.Dockerfile'
    
      - script: |
          docker container create --name $(container) $(image) 
          docker container cp $(container):./app/out $(Agent.TempDirectory)
          docker container rm -f $(container)
        displayName: 'Copy docker output to temp folder'
    
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Agent.TempDirectory)
          contents: out/*.zip
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
    
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: app-bundle

  
  # CI DEPLOYMENT
  ###################################################################################################################
  - stage: CI
    displayName: Deploy Resources CI
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    
    jobs:
      - deployment: DeployApp
        displayName: 'Deploy resources'
        pool: Private Docker
        environment: fusion-ci
        variables:
          portalUrl: 'https://pro-s-portal-ci.azurewebsites.net'
          tokenResource: '5a842df8-3238-415d-b168-9f16a6a6031b'
        
        strategy:
          runOnce:
            deploy:
              steps: 
              - task: FusionApp@1
                displayName: 'Deploying app bundle for resources'
                condition: succeeded()
                inputs:
                  fusionCredentials: 'Fusion test'
                  tokenResource: '5a842df8-3238-415d-b168-9f16a6a6031b'
                  portalUrl: 'https://pro-s-portal-ci.azurewebsites.net'
                  action: deploy
                  appKey: resources
                  bundlePath: '$(pipeline.workspace)/app-bundle/resources.zip'
                  ignoreVersionConflict: true
                  forceReplaceExisting: true