name: pr-cleanup-$(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none
# schedules:
#   - cron: 0 18 * * *
#     always: true
#     branches:
#       include:
#         - master
#     displayName: Daily pull request env cleanup

jobs:
  - deployment: DeployPR
    displayName: 'Remove pull request environment artifacts'
    pool: Private Docker
    environment: fusion-resources-pr.fusion-resources-app-pr
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: |
              $prs = Invoke-RestMethod -Uri "https://api.github.com/repos/equinor/fusion-app-resources/pulls?state=active&per_page=100" -Headers @{Authorization = "Bearer $(githubPatToken)"}

              if ($prs -eq $null) { throw "Could not load pull requests, terminating" }

              $activePRs = $prs | select -ExpandProperty number
              Write-Host "Located active pull requests" 
              Write-Host $activePRs

              Write-Output "##vso[task.setvariable variable=activePrs]$([string]::Join(",", $activePRs))"
            displayName: Detect active pull requests

          - task: AzurePowerShell@4
            displayName: 'Deploy Function ARM template'
            inputs:
              azureSubscription: 'PROJECT_PORTAL (63b791ae-b2bc-41a1-ac66-806c4e69bffe)'
              ScriptType: 'InlineScript'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
              Inline: |                
                $activePRs = "$(activePrs)".Split(",")

                $prDbs = Get-AzResource -ResourceType "Microsoft.Sql/servers/databases" -Tag @{"fusion-app" = "resources"; "fusion-app-env" = "pr" }

                foreach ($db in $prDbs) {
                    Write-Host "Processing db: $($db.Name)"
                    $dbPrNumber = $db.Tags["pr"]
                    if ($null -eq $dbPrNumber) { 
                        Write-Host "`tCould not locate pull request number for db, skipping"
                        continue
                    }
                    Write-Host "`tLocated pull request number $dbPrNumber..."

                    if ($activePRs.Contains($dbPrNumber)) {
                        Write-Host "`tPull request still active, skipping..."
                        continue
                    } else {
                        Write-Host "`tPull request not active, deleting db..."
                        
                    }    
                }





