version: "3.7"
services:
  resources:
    image: fusion-resources-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - 8080:3000
    volumes:
      - .:/app:rw
      - /app/node_modules