// <auto-generated />
using System;
using Fusion.Summary.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fusion.Summary.Api.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240703113355_SummaryReport")]
    partial class SummaryReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbDepartment", b =>
                {
                    b.Property<string>("DepartmentSapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullDepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResourceOwnerAzureUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepartmentSapId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbSummaryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationChangesAwaitingTaskOwnerAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageTimeToHandleRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapacityInUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentSapId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumberOfOpenRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsLastPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsStartingInLessThanThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsStartingInMoreThanThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProjectChangesAffectingNextThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSapId", "PeriodType", "Period")
                        .IsUnique();

                    b.ToTable("SummaryReports", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbSummaryReport", b =>
                {
                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbEndingPosition", "PositionsEnding", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SummaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SummaryReportId");

                            b1.ToTable("PersonnelMoreThan100PercentFTEs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SummaryReportId");
                        });

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbPersonnelMoreThan100PercentFTE", "PersonnelMoreThan100PercentFTE", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FTE")
                                .HasColumnType("int");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SummaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SummaryReportId");

                            b1.ToTable("EndingPositions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SummaryReportId");
                        });

                    b.Navigation("PersonnelMoreThan100PercentFTE");

                    b.Navigation("PositionsEnding");
                });
#pragma warning restore 612, 618
        }
    }
}
