// <auto-generated />
using System;
using Fusion.Summary.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fusion.Summary.Api.Database.Migrations
{
    [DbContext(typeof(SummaryDbContext))]
    [Migration("20250730120409_OpenRequestsWorkload_to_db_column")]
    partial class OpenRequestsWorkload_to_db_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbDepartment", b =>
                {
                    b.Property<string>("DepartmentSapId")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("DelegateResourceOwnersAzureUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ResourceOwnersAzureUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentSapId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AssignedAdminsAzureUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DirectorAzureUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgProjectExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrgProjectExternalId")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbWeeklySummaryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationChangesAwaitingTaskOwnerAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageTimeToHandleRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapacityInUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentSapId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumberOfOpenRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsLastPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsStartingInLessThanThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfRequestsStartingInMoreThanThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenRequestsWorkload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectChangesAffectingNextThreeMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSapId", "Period")
                        .IsUnique();

                    b.ToTable("WeeklySummaryReports", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbWeeklyTaskOwnerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionsAwaitingTaskOwnerAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("WeeklyTaskOwnerReports", (string)null);
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbWeeklySummaryReport", b =>
                {
                    b.HasOne("Fusion.Summary.Api.Database.Models.DbDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentSapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbEndingPosition", "PositionsEnding", b1 =>
                        {
                            b1.Property<Guid>("DbWeeklySummaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DbWeeklySummaryReportId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklySummaryReports");

                            b1.ToJson("PositionsEnding");

                            b1.WithOwner()
                                .HasForeignKey("DbWeeklySummaryReportId");
                        });

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbPersonnelMoreThan100PercentFTE", "PersonnelMoreThan100PercentFTE", b1 =>
                        {
                            b1.Property<Guid>("DbWeeklySummaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<double>("FTE")
                                .HasColumnType("float");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DbWeeklySummaryReportId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklySummaryReports");

                            b1.ToJson("PersonnelMoreThan100PercentFTE");

                            b1.WithOwner()
                                .HasForeignKey("DbWeeklySummaryReportId");
                        });

                    b.Navigation("Department");

                    b.Navigation("PersonnelMoreThan100PercentFTE");

                    b.Navigation("PositionsEnding");
                });

            modelBuilder.Entity("Fusion.Summary.Api.Database.Models.DbWeeklyTaskOwnerReport", b =>
                {
                    b.HasOne("Fusion.Summary.Api.Database.Models.DbProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbAdminAccessExpiring", "AdminAccessExpiringInLessThanThreeMonths", b1 =>
                        {
                            b1.Property<Guid>("DbWeeklyTaskOwnerReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<Guid>("AzureUniqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("DbWeeklyTaskOwnerReportId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklyTaskOwnerReports");

                            b1.ToJson("AdminAccessExpiringInLessThanThreeMonths");

                            b1.WithOwner()
                                .HasForeignKey("DbWeeklyTaskOwnerReportId");
                        });

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbPositionAllocationEnding", "PositionAllocationsEndingInNextThreeMonths", b1 =>
                        {
                            b1.Property<Guid>("DbWeeklyTaskOwnerReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("PositionAppliesTo")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PositionExternalId")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("PositionName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("PositionNameDetailed")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("DbWeeklyTaskOwnerReportId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklyTaskOwnerReports");

                            b1.ToJson("PositionAllocationsEndingInNextThreeMonths");

                            b1.WithOwner()
                                .HasForeignKey("DbWeeklyTaskOwnerReportId");
                        });

                    b.OwnsMany("Fusion.Summary.Api.Database.Models.DbTBNPositionStartingSoon", "TBNPositionsStartingInLessThanThreeMonths", b1 =>
                        {
                            b1.Property<Guid>("DbWeeklyTaskOwnerReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("PositionAppliesFrom")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PositionExternalId")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("PositionName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("PositionNameDetailed")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("DbWeeklyTaskOwnerReportId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklyTaskOwnerReports");

                            b1.ToJson("TBNPositionsStartingInLessThanThreeMonths");

                            b1.WithOwner()
                                .HasForeignKey("DbWeeklyTaskOwnerReportId");
                        });

                    b.Navigation("AdminAccessExpiringInLessThanThreeMonths");

                    b.Navigation("PositionAllocationsEndingInNextThreeMonths");

                    b.Navigation("Project");

                    b.Navigation("TBNPositionsStartingInLessThanThreeMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
