param(
    [string]$applicationId,
    [string]$keyVaultName
)

$SECRET_NAME = "AzureAd--ClientSecret"
$AAD_APP_ID = $applicationId
$SECRETVAULTNAME = $keyVaultName


## Cleanup old keys..
$secretWithVersions = Get-AzKeyVaultSecret -VaultName $SECRETVAULTNAME -Name $SECRET_NAME -IncludeVersions
foreach ($s in $secretWithVersions) {    
    Write-Host "Processing key: $($s.Id)"
    $isAutoGenerated = $null -ne $s.Tags -and $s.Tags["auto-generated"] -eq "true"

    if ($isAutoGenerated) {
        $keyId = $s.Tags["keyId"]
        $isDeleted = $s.Tags.ContainsKey("deleted")

        if ([string]::IsNullOrEmpty($keyId)) {
            Write-Host "`tCould not locate any key id, skipping"
        }

        if ($isDeleted -eq $true) { Write-Host "`tAlready deleted @ $($s.Tags["deleted"])"; continue }
        if ($s.Expires -lt (Get-Date)) {            
            Write-Host "`tExpired secret.. Deleting key id: $keyId"
            $newTags = $s.Tags
            $newTags["deleted"] = (Get-Date).ToString()
            Update-AzKeyVaultSecret $s -Version $s.Version -Tag $newTags

            Remove-AzADAppCredential -ApplicationId $AAD_APP_ID -KeyId $keyId -Force
        }
    } else {
        Write-Host "Non auto generated key, skipping"
    }
}