param(
    [string]$applicationId,
    [string]$keyVaultName
)

$SECRET_NAME = "AzureAd--ClientSecret"
$AAD_APP_ID = $applicationId
$SECRETVAULTNAME = $keyVaultName

Write-Host "Application ID: $AAD_APP_ID"
Write-Host "Key vault: $SECRETVAULTNAME"

$secret = Get-AzKeyVaultSecret -VaultName $SECRETVAULTNAME -Name $SECRET_NAME

$generateNew = $false

if ($null -ne $secret.Tags -and $secret.Tags["auto-generated"] -eq "true") {
    Write-Host "Located autogenerated secret"

    ## Check expires flag
    $delta = $secret.Expires - (Get-Date)

    Write-Host "Secret expires in $($delta.Days) days"
    if ($delta.Days -lt 60) {
        $generateNew = $true
    }

} else {
    Write-Host "Secret not autogenerated, creating new..."
    $generateNew = $true
}

if (-not $generateNew) {
    Write-Host "No need to generate secret..."
    return
} else {
    Write-Host "Generating new secret..."
}

## Generate secret on aad app
$startDate = Get-Date
$endDate = $startDate.AddMonths(6)

$credential = @{
    DisplayName = "Resources - $keyVaultName"
    StartDateTime = $startDate
    EndDateTime = $endDate
}

Get-Command -Name "New-AzADAppCredential"

$app = Get-AzADAppCredential -ApplicationId $AAD_APP_ID
$app
$newSecret = New-AzADAppCredential -ApplicationObject $app -PasswordCredentials $credential

Write-Host "New secret [$($newSecret.Hint)************] generated with expiration date $endDate, key id [$($newSecret.KeyId)]"

$secretValue = ConvertTo-SecureString -String $newSecret.SecretText -AsPlainText -Force
## Add to key vault
Set-AzKeyVaultSecret -VaultName $SECRETVAULTNAME -Name $SECRET_NAME -SecretValue $secretValue -Expires $endDate -Tag @{ "auto-generated" = "true"; "keyId" = $newSecret.KeyId; "hint" = $newSecret.Hint }


