name: JS App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    # Removing path options, as github does not support having required checks and path filters.

    # paths: 
    # - src/backend/**

jobs:
  pre_js_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["src/frontend/**"]'

  build_js_app:
    needs: pre_js_job
    if: ${{ needs.pre_js_job.outputs.should_skip != 'true' }}

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: src/frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    