name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # paths: 
    # - src/backend/**

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          do_not_skip: '["src/backend/**"]'

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}

    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        working-directory: src/backend

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger GitHubActions
